export type PlanZoneDef = {
  id: string;
  label: string;
  x: number;
  y: number;
  w: number;
  h: number;
  fill: string;
  textColor?: string;
  roomSlug?: string;
  subtitle?: string;
};

export type PlanFloorDef = {
  id: string;
  label: string;
  zones: PlanZoneDef[];
};

export type PlanBuildingDef = {
  id: string;
  label: string;
  floors: PlanFloorDef[];
};

/** Couleurs inspirées du plan BMS Cité */
export const PLAN_COLORS = {
  circulation: "#1e3a5f",
  hall: "#7c3aed",
  restauration: "#38bdf8",
  polyvalenteLarge: "#2563eb",
  polyvalente: "#60a5fa",
  salons: "#a78bfa",
  studios: "#ea580c",
  enfants: "#22c55e",
  exterieur: "#86efac",
  auditorium: "#1d4ed8",
  structure: "#e2e8f0",
} as const;

export const PLAN_BUILDINGS: PlanBuildingDef[] = [
  {
    id: "batiment-1",
    label: "Bâtiment 1",
    floors: [
      {
        id: "rdc",
        label: "RDC",
        zones: [
          {
            id: "ext-nord",
            label: "Extérieurs",
            x: 4,
            y: 4,
            w: 192,
            h: 14,
            fill: PLAN_COLORS.exterieur,
            textColor: "#14532d",
          },
          {
            id: "hall",
            label: "Hall",
            x: 4,
            y: 22,
            w: 36,
            h: 50,
            fill: PLAN_COLORS.hall,
          },
          {
            id: "circ-1",
            label: "Circulations",
            x: 42,
            y: 22,
            w: 10,
            h: 110,
            fill: PLAN_COLORS.circulation,
            textColor: "#93c5fd",
          },
          {
            id: "cafeteria",
            label: "Cafétéria",
            x: 54,
            y: 22,
            w: 48,
            h: 28,
            fill: PLAN_COLORS.restauration,
            textColor: "#0c4a6e",
          },
          {
            id: "restaurant",
            label: "Restaurant",
            x: 54,
            y: 54,
            w: 48,
            h: 32,
            fill: PLAN_COLORS.restauration,
            textColor: "#0c4a6e",
          },
          {
            id: "magasin",
            label: "Magasin",
            x: 54,
            y: 90,
            w: 48,
            h: 20,
            fill: PLAN_COLORS.restauration,
            textColor: "#0c4a6e",
          },
          {
            id: "circ-2",
            label: "Circulations",
            x: 104,
            y: 22,
            w: 10,
            h: 88,
            fill: PLAN_COLORS.circulation,
            textColor: "#93c5fd",
          },
          {
            id: "emission-tv",
            label: "Émission TV",
            x: 116,
            y: 22,
            w: 38,
            h: 28,
            fill: PLAN_COLORS.studios,
            roomSlug: "emission-tv",
          },
          {
            id: "plateau-tv",
            label: "Plateau TV",
            x: 156,
            y: 22,
            w: 40,
            h: 28,
            fill: PLAN_COLORS.studios,
            roomSlug: "plateau-tv-fond-vert",
          },
          {
            id: "debat-tv",
            label: "Débat TV",
            x: 116,
            y: 54,
            w: 38,
            h: 24,
            fill: PLAN_COLORS.studios,
            roomSlug: "debat-tv-table-ronde",
          },
          {
            id: "audio",
            label: "Audio",
            x: 156,
            y: 54,
            w: 40,
            h: 24,
            fill: PLAN_COLORS.studios,
            roomSlug: "enregistrement-audio",
          },
          {
            id: "circ-3",
            label: "Circulations",
            x: 116,
            y: 82,
            w: 80,
            h: 8,
            fill: PLAN_COLORS.circulation,
            textColor: "#93c5fd",
          },
          {
            id: "amethyste",
            label: "Améthyste",
            x: 116,
            y: 92,
            w: 38,
            h: 22,
            fill: PLAN_COLORS.enfants,
            roomSlug: "amethyste",
          },
          {
            id: "crysolithe",
            label: "Crysolithe",
            x: 156,
            y: 92,
            w: 40,
            h: 22,
            fill: PLAN_COLORS.enfants,
            roomSlug: "crysolithe",
          },
          {
            id: "jaspe",
            label: "Jaspe",
            x: 116,
            y: 116,
            w: 24,
            h: 16,
            fill: PLAN_COLORS.enfants,
            roomSlug: "jaspe",
          },
          {
            id: "hyacinthe",
            label: "Hyacinthe",
            x: 142,
            y: 116,
            w: 28,
            h: 16,
            fill: PLAN_COLORS.enfants,
            roomSlug: "hyacinthe",
          },
          {
            id: "agathe",
            label: "Agathe",
            x: 172,
            y: 116,
            w: 24,
            h: 16,
            fill: PLAN_COLORS.enfants,
            roomSlug: "agathe",
          },
          {
            id: "beril",
            label: "Béril",
            x: 4,
            y: 76,
            w: 36,
            h: 56,
            fill: PLAN_COLORS.enfants,
            roomSlug: "beril",
          },
          {
            id: "ext-sud",
            label: "Extérieurs",
            x: 4,
            y: 134,
            w: 192,
            h: 10,
            fill: PLAN_COLORS.exterieur,
            textColor: "#14532d",
          },
        ],
      },
      {
        id: "r1",
        label: "R+1",
        zones: [
          {
            id: "circ-r1-1",
            label: "Circulations",
            x: 4,
            y: 4,
            w: 192,
            h: 10,
            fill: PLAN_COLORS.circulation,
            textColor: "#93c5fd",
          },
          {
            id: "diamant",
            label: "Diamant",
            x: 4,
            y: 18,
            w: 58,
            h: 52,
            fill: PLAN_COLORS.polyvalenteLarge,
            roomSlug: "diamant",
            subtitle: "500 m²",
          },
          {
            id: "onyx",
            label: "Onyx",
            x: 66,
            y: 18,
            w: 58,
            h: 52,
            fill: PLAN_COLORS.polyvalenteLarge,
            roomSlug: "onyx",
            subtitle: "500 m²",
          },
          {
            id: "diamant-onyx",
            label: "Diamant & Onyx",
            x: 4,
            y: 74,
            w: 120,
            h: 14,
            fill: "#1e40af",
            roomSlug: "diamant-onyx",
            subtitle: "1 000 m²",
          },
          {
            id: "circ-r1-2",
            label: "Circulations",
            x: 128,
            y: 18,
            w: 10,
            h: 70,
            fill: PLAN_COLORS.circulation,
            textColor: "#93c5fd",
          },
          {
            id: "sardoine",
            label: "Sardoine",
            x: 140,
            y: 18,
            w: 28,
            h: 24,
            fill: PLAN_COLORS.polyvalente,
            roomSlug: "sardoine",
          },
          {
            id: "saphir",
            label: "Saphir",
            x: 170,
            y: 18,
            w: 26,
            h: 24,
            fill: PLAN_COLORS.polyvalente,
            roomSlug: "saphir",
          },
          {
            id: "topaze",
            label: "Topaze",
            x: 140,
            y: 46,
            w: 56,
            h: 20,
            fill: PLAN_COLORS.polyvalente,
            roomSlug: "topaze",
          },
          {
            id: "or",
            label: "Or",
            x: 140,
            y: 70,
            w: 56,
            h: 18,
            fill: PLAN_COLORS.polyvalente,
            roomSlug: "or",
          },
          {
            id: "rosaces",
            label: "Rosaces",
            x: 4,
            y: 92,
            w: 36,
            h: 28,
            fill: PLAN_COLORS.hall,
          },
          {
            id: "emeraude",
            label: "Emeraude",
            x: 44,
            y: 92,
            w: 28,
            h: 28,
            fill: PLAN_COLORS.salons,
            roomSlug: "emeraude",
          },
          {
            id: "escarboucle",
            label: "Escarboucle",
            x: 76,
            y: 92,
            w: 28,
            h: 28,
            fill: PLAN_COLORS.salons,
            roomSlug: "escarboucle",
          },
          {
            id: "sardius",
            label: "Sardius",
            x: 108,
            y: 92,
            w: 24,
            h: 28,
            fill: PLAN_COLORS.salons,
            roomSlug: "sardius",
          },
          {
            id: "sardonyx",
            label: "Sardonyx",
            x: 136,
            y: 92,
            w: 20,
            h: 28,
            fill: PLAN_COLORS.salons,
            roomSlug: "sardonyx",
          },
          {
            id: "circ-r1-3",
            label: "Circulations",
            x: 4,
            y: 124,
            w: 192,
            h: 10,
            fill: PLAN_COLORS.circulation,
            textColor: "#93c5fd",
          },
        ],
      },
    ],
  },
  {
    id: "batiment-2",
    label: "Bâtiment 2",
    floors: [
      {
        id: "rdc",
        label: "RDC",
        zones: [
          {
            id: "circ-b2-1",
            label: "Circulations",
            x: 4,
            y: 4,
            w: 192,
            h: 12,
            fill: PLAN_COLORS.circulation,
            textColor: "#93c5fd",
          },
          {
            id: "auditorium-rdc",
            label: "Auditorium",
            x: 28,
            y: 20,
            w: 144,
            h: 88,
            fill: PLAN_COLORS.auditorium,
            roomSlug: "auditorium",
            subtitle: "Parterre",
          },
          {
            id: "rubis",
            label: "Rubis",
            x: 4,
            y: 48,
            w: 20,
            h: 36,
            fill: PLAN_COLORS.polyvalente,
          },
          {
            id: "ext-b2",
            label: "Extérieurs",
            x: 4,
            y: 112,
            w: 192,
            h: 16,
            fill: PLAN_COLORS.exterieur,
            textColor: "#14532d",
          },
        ],
      },
      {
        id: "r1",
        label: "R+1",
        zones: [
          {
            id: "circ-b2-r1",
            label: "Circulations",
            x: 4,
            y: 4,
            w: 192,
            h: 12,
            fill: PLAN_COLORS.circulation,
            textColor: "#93c5fd",
          },
          {
            id: "auditorium-r1",
            label: "Auditorium",
            x: 20,
            y: 20,
            w: 160,
            h: 96,
            fill: PLAN_COLORS.auditorium,
            roomSlug: "auditorium",
            subtitle: "Gradins",
          },
        ],
      },
      {
        id: "r2",
        label: "R+2",
        zones: [
          {
            id: "circ-b2-r2",
            label: "Circulations",
            x: 4,
            y: 4,
            w: 192,
            h: 12,
            fill: PLAN_COLORS.circulation,
            textColor: "#93c5fd",
          },
          {
            id: "auditorium-r2",
            label: "Auditorium",
            x: 32,
            y: 20,
            w: 136,
            h: 72,
            fill: PLAN_COLORS.auditorium,
            roomSlug: "auditorium",
            subtitle: "Balcons",
          },
          {
            id: "safran",
            label: "Safran",
            x: 4,
            y: 24,
            w: 24,
            h: 20,
            fill: PLAN_COLORS.salons,
          },
          {
            id: "cinnamone",
            label: "Cinnamone",
            x: 4,
            y: 48,
            w: 24,
            h: 20,
            fill: PLAN_COLORS.salons,
          },
          {
            id: "aloes",
            label: "Aloès",
            x: 4,
            y: 72,
            w: 24,
            h: 20,
            fill: PLAN_COLORS.salons,
          },
          {
            id: "myrrhe",
            label: "Myrrhe",
            x: 172,
            y: 24,
            w: 24,
            h: 20,
            fill: PLAN_COLORS.salons,
          },
          {
            id: "symphonie",
            label: "Symphonie",
            x: 172,
            y: 48,
            w: 24,
            h: 44,
            fill: PLAN_COLORS.salons,
          },
        ],
      },
    ],
  },
];

export const PLAN_LEGEND = [
  { color: PLAN_COLORS.polyvalenteLarge, label: "Salles polyvalentes" },
  { color: PLAN_COLORS.salons, label: "Salons & réunions" },
  { color: PLAN_COLORS.studios, label: "Studios TV" },
  { color: PLAN_COLORS.enfants, label: "Espaces enfants" },
  { color: PLAN_COLORS.auditorium, label: "Auditorium" },
  { color: PLAN_COLORS.hall, label: "Espaces communs" },
  { color: PLAN_COLORS.circulation, label: "Circulations" },
] as const;
