import type { Room } from "@/types/database";

const FALLBACK_SERVICE_IDS = {
  evenementiel: "00000000-0000-0000-0000-000000000001",
  salons: "00000000-0000-0000-0000-000000000002",
  production: "00000000-0000-0000-0000-000000000003",
  enfants: "00000000-0000-0000-0000-000000000004",
} as const;

export const FALLBACK_ROOMS: Room[] = [
  { id: "1", slug: "auditorium", name: "Auditorium", room_type: "auditorium", surface_sqm: 4000, capacity: 3500, pricing_type: "quote", base_price: null, service_id: FALLBACK_SERVICE_IDS.evenementiel, description: "Grand auditorium modulable sur plusieurs niveaux, scène 400 m², mur LED et régie professionnelle.", is_active: true, equipment: ["Mur LED géant", "Régie lumière & son", "Scène 400 m²", "Accès PMR"], requires_second_approval: true, services: { id: FALLBACK_SERVICE_IDS.evenementiel, name: "Événementiel", description: null } },
  { id: "2", slug: "diamant", name: "Diamant", room_type: "salle_polyvalente", surface_sqm: 500, capacity: 500, pricing_type: "from", base_price: 3500, service_id: FALLBACK_SERVICE_IDS.evenementiel, description: "Salle polyvalente 500 m², mur LED, régie lumière/son. Configurations conférence, banquet ou cocktail.", is_active: true, equipment: ["Mur LED", "Régie lumière & son", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.evenementiel, name: "Événementiel", description: null } },
  { id: "3", slug: "onyx", name: "Onyx", room_type: "salle_polyvalente", surface_sqm: 500, capacity: 500, pricing_type: "from", base_price: 3500, service_id: FALLBACK_SERVICE_IDS.evenementiel, description: "Salle polyvalente 500 m², mur LED, régie lumière/son. Configurations conférence, banquet ou cocktail.", is_active: true, equipment: ["Mur LED", "Régie lumière & son", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.evenementiel, name: "Événementiel", description: null } },
  { id: "4", slug: "diamant-onyx", name: "Diamant & Onyx", room_type: "salle_polyvalente", surface_sqm: 1000, capacity: 1000, pricing_type: "from", base_price: 7000, service_id: FALLBACK_SERVICE_IDS.evenementiel, description: "Ensemble modulable Diamant & Onyx 1 000 m². Conférences, banquets et cocktails jusqu'à 1 000 personnes.", is_active: true, equipment: ["Mur LED", "Régie lumière & son", "Modulable", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.evenementiel, name: "Événementiel", description: null } },
  { id: "5", slug: "sardoine", name: "Sardoine", room_type: "salle_polyvalente", surface_sqm: 200, capacity: 200, pricing_type: "from", base_price: 1500, service_id: FALLBACK_SERVICE_IDS.evenementiel, description: "Salle polyvalente 200 m², lumière naturelle, vidéoprojecteur. Séminaires et formations jusqu'à 200 personnes.", is_active: true, equipment: ["Vidéoprojecteur", "Climatisation", "Lumière naturelle", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.evenementiel, name: "Événementiel", description: null } },
  { id: "6", slug: "saphir", name: "Saphir", room_type: "salle_polyvalente", surface_sqm: 200, capacity: 200, pricing_type: "from", base_price: 1500, service_id: FALLBACK_SERVICE_IDS.evenementiel, description: "Salle polyvalente 200 m², lumière naturelle, vidéoprojecteur. Conférence, banquet ou cocktail jusqu'à 200 personnes.", is_active: true, equipment: ["Vidéoprojecteur", "Écran de projection", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.evenementiel, name: "Événementiel", description: null } },
  { id: "7", slug: "topaze", name: "Topaze", room_type: "salle_polyvalente", surface_sqm: 400, capacity: 400, pricing_type: "from", base_price: 2000, service_id: FALLBACK_SERVICE_IDS.evenementiel, description: "Salle polyvalente 400 m², lumière naturelle, éclairage modulable. Banquet, conférence ou cocktail jusqu'à 400 personnes.", is_active: true, equipment: ["Vidéoprojecteur", "Éclairage d'ambiance", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.evenementiel, name: "Événementiel", description: null } },
  { id: "8", slug: "or", name: "Or", room_type: "salle_polyvalente", surface_sqm: 200, capacity: 200, pricing_type: "from", base_price: 1500, service_id: FALLBACK_SERVICE_IDS.evenementiel, description: "Salle polyvalente 200 m², lumière naturelle, vidéoprojecteur. Conférence ou réunion jusqu'à 200 personnes.", is_active: true, equipment: ["Vidéoprojecteur", "Écran de projection", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.evenementiel, name: "Événementiel", description: null } },
  { id: "9", slug: "emeraude", name: "Emeraude", room_type: "salon", surface_sqm: 60, capacity: 40, pricing_type: "from", base_price: 390, service_id: FALLBACK_SERVICE_IDS.salons, description: "Salon lounge 60 m², lumière naturelle, écran TV. Réunions informelles jusqu'à 40 personnes.", is_active: true, equipment: ["Écran TV", "Canapés modulables", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.salons, name: "Salons & Réunions", description: null } },
  { id: "10", slug: "escarboucle", name: "Escarboucle", room_type: "salon", surface_sqm: 50, capacity: 20, pricing_type: "from", base_price: 330, service_id: FALLBACK_SERVICE_IDS.salons, description: "Salon de réunion 50 m², lumière naturelle, table de conférence. Jusqu'à 20 personnes.", is_active: true, equipment: ["Table de conférence", "Prises intégrées", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.salons, name: "Salons & Réunions", description: null } },
  { id: "11", slug: "sardonyx", name: "Sardonyx", room_type: "salon", surface_sqm: 30, capacity: 12, pricing_type: "from", base_price: 200, service_id: FALLBACK_SERVICE_IDS.salons, description: "Petit salon de réunion 30 m², climatisé. Jusqu'à 12 personnes.", is_active: true, equipment: ["Table de réunion", "Écran TV", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.salons, name: "Salons & Réunions", description: null } },
  { id: "12", slug: "sardius", name: "Sardius", room_type: "salon", surface_sqm: 40, capacity: 30, pricing_type: "from", base_price: 260, service_id: FALLBACK_SERVICE_IDS.salons, description: "Salon de réunion 40 m², lumière naturelle, table de conférence. Jusqu'à 30 personnes.", is_active: true, equipment: ["Table de conférence", "Prises intégrées", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.salons, name: "Salons & Réunions", description: null } },
  { id: "13", slug: "emission-tv", name: "Émission TV", room_type: "studio", surface_sqm: 110, capacity: 50, pricing_type: "quote", base_price: null, service_id: FALLBACK_SERVICE_IDS.production, description: "Studio d'émission TV 110 m², plateau et public jusqu'à 50 personnes.", is_active: true, equipment: ["Caméras", "Régie vidéo", "Éclairage studio", "Sonorisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.production, name: "Production audiovisuelle", description: null } },
  { id: "14", slug: "plateau-tv-fond-vert", name: "Plateau TV fond vert", room_type: "studio", surface_sqm: 50, capacity: 10, pricing_type: "quote", base_price: null, service_id: FALLBACK_SERVICE_IDS.production, description: "Studio TV avec fond vert 50 m². Jusqu'à 10 personnes.", is_active: true, equipment: ["Fond vert", "Caméras", "Régie vidéo", "Éclairage studio", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.production, name: "Production audiovisuelle", description: null } },
  { id: "15", slug: "debat-tv-table-ronde", name: "Débat TV table ronde", room_type: "studio", surface_sqm: 30, capacity: 7, pricing_type: "quote", base_price: null, service_id: FALLBACK_SERVICE_IDS.production, description: "Studio débat TV avec table ronde 30 m². Jusqu'à 7 personnes.", is_active: true, equipment: ["Table ronde", "Caméras", "Régie vidéo", "Sonorisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.production, name: "Production audiovisuelle", description: null } },
  { id: "16", slug: "enregistrement-audio", name: "Enregistrement audio", room_type: "studio", surface_sqm: 40, capacity: 10, pricing_type: "quote", base_price: null, service_id: FALLBACK_SERVICE_IDS.production, description: "Studio d'enregistrement audio 40 m². Jusqu'à 10 personnes.", is_active: true, equipment: ["Insonorisation", "Microphones", "Régie son", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.production, name: "Production audiovisuelle", description: null } },
  { id: "17", slug: "amethyste", name: "Améthyste", room_type: "espace_enfants", surface_sqm: 85, capacity: 50, pricing_type: "from", base_price: 950, service_id: FALLBACK_SERVICE_IDS.enfants, description: "Espace enfants modulable 85 m². Ateliers et animations jusqu'à 50 enfants.", is_active: true, equipment: ["Jeux", "Tables enfants", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.enfants, name: "Espace enfants", description: null } },
  { id: "18", slug: "crysolithe", name: "Crysolithe", room_type: "espace_enfants", surface_sqm: 85, capacity: 50, pricing_type: "from", base_price: 950, service_id: FALLBACK_SERVICE_IDS.enfants, description: "Espace enfants 85 m², configuration classe. Ateliers et formations jusqu'à 50 enfants.", is_active: true, equipment: ["Écran mural", "Tables modulables", "Chaises", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.enfants, name: "Espace enfants", description: null } },
  { id: "19", slug: "jaspe", name: "Jaspe", room_type: "espace_enfants", surface_sqm: 85, capacity: 50, pricing_type: "from", base_price: 950, service_id: FALLBACK_SERVICE_IDS.enfants, description: "Espace enfants modulable 85 m². Ateliers et animations jusqu'à 50 enfants.", is_active: true, equipment: ["Jeux", "Tables enfants", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.enfants, name: "Espace enfants", description: null } },
  { id: "20", slug: "hyacinthe", name: "Hyacinthe", room_type: "espace_enfants", surface_sqm: 160, capacity: 100, pricing_type: "from", base_price: 1000, service_id: FALLBACK_SERVICE_IDS.enfants, description: "Grand espace enfants 160 m². Ateliers et animations jusqu'à 100 enfants.", is_active: true, equipment: ["Jeux", "Tables enfants", "Mobilier modulable", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.enfants, name: "Espace enfants", description: null } },
  { id: "21", slug: "agathe", name: "Agathe", room_type: "espace_enfants", surface_sqm: 120, capacity: null, pricing_type: "from", base_price: 950, service_id: FALLBACK_SERVICE_IDS.enfants, description: "Espace enfants ludique 120 m², piscine à balles et jeux. Jusqu'à 50 enfants.", is_active: true, equipment: ["Piscine à balles", "Jeux", "Panier de basket", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.enfants, name: "Espace enfants", description: null } },
  { id: "22", slug: "beril", name: "Béril", room_type: "espace_enfants", surface_sqm: 85, capacity: null, pricing_type: "from", base_price: 950, service_id: FALLBACK_SERVICE_IDS.enfants, description: "Espace enfants 85 m², configuration classe. Jusqu'à 40 enfants.", is_active: true, equipment: ["Tables enfants", "Chaises", "Climatisation", "Accès PMR"], services: { id: FALLBACK_SERVICE_IDS.enfants, name: "Espace enfants", description: null } },
];
